load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "day11",
    main_class = "aoc2018.day11.Day11Kt",
    srcs = glob(["*.kt"]),
    deps = [
        "//src/main/kotlin/grid",
        "//src/main/kotlin/util",
    ],
    resources = [
        "//src/main/resources/aoc2018/day11",
    ],
)
